
import { SpecialBlockData } from "../../../data/consts.js"
import { BlockMappings, BlockMappingsReverse } from "./mappings.js"
import palette_fix from './palette_fix.js'
import { BlockIdentifier } from "../../index.js"

export default class BlockList {
    public static Special = [
        'gravity_left',
        'gravity_up',
        'gravity_right',
        'gravity_down',
        'gravity_dot',
        'gravity_slow_dot',
        'invisible_gravity_left',
        'invisible_gravity_up',
        'invisible_gravity_right',
        'invisible_gravity_down',
        'invisible_gravity_dot',
        'invisible_gravity_slow_dot',
        'boost_left',
        'boost_up',
        'boost_right',
        'boost_down',
        'climbable_vine_vertical',
        'climbable_vine_horizontal',
        'climbable_chain_light_vertical',
        'climbable_chain_light_horizontal',
        'climbable_chain_dark_vertical',
        'climbable_chain_dark_horizontal',
        'climbable_ladder_metal',
        'climbable_ladder_wood',
        'climbable_rope_vertical',
        'climbable_rope_horizontal',
        'climbable_ladder_stalk_small',
        'climbable_ladder_stalk_large',
        'climbable_lattice_vine',
        'special_hologram',
        'special_diamond',
        'special_cake',
        'crown_gold',
        'crown_silver',
        'crown_gold_door',
        'crown_gold_gate',
        'crown_silver_door',
        'crown_silver_gate',
        'key_red',
        'key_green',
        'key_blue',
        'key_cyan',
        'key_magenta',
        'key_yellow',
        'key_red_door',
        'key_green_door',
        'key_blue_door',
        'key_cyan_door',
        'key_magenta_door',
        'key_yellow_door',
        'key_red_gate',
        'key_green_gate',
        'key_blue_gate',
        'key_cyan_gate',
        'key_magenta_gate',
        'key_yellow_gate',
        'coin_gold',
        'coin_blue',
        'coin_gold_door',
        'coin_blue_door',
        'coin_gold_gate',
        'coin_blue_gate',
        'effects_jump_height',
        'effects_fly',
        'effects_speed',
        'effects_invulnerability',
        'effects_curse',
        'effects_zombie',
        'effects_gravityforce',
        'effects_multi_jump',
        'effects_gravity_left',
        'effects_gravity_up',
        'effects_gravity_right',
        'effects_gravity_down',
        'effects_gravity_off',
        'effects_off',
        'effects_zombie_door',
        'effects_zombie_gate',
        'tool_spawn_lobby',
        'tool_checkpoint',
        'tool_reset',
        'tool_god_mode_activator',
        'tool_portal_world_spawn',
        'tool_activate_minimap',
        'sign_normal',
        'sign_red',
        'sign_green',
        'sign_blue',
        'sign_gold',
        'portal',
        'portal_invisible',
        'portal_world',
        'liquid_water',
        'liquid_waste',
        'liquid_lava',
        'liquid_mud',
        'switch_local_toggle',
        'switch_local_activator',
        'switch_local_resetter',
        'switch_local_door',
        'switch_local_gate',
        'switch_global_toggle',
        'switch_global_activator',
        'switch_global_resetter',
        'switch_global_door',
        'switch_global_gate',
        'hazard_spikes_left',
        'hazard_spikes_up',
        'hazard_spikes_right',
        'hazard_spikes_down',
        'hazard_spikes_center',
        'hazard_fire',
        'hazard_death_door',
        'hazard_death_gate',
        'team_effect_none',
        'team_effect_red',
        'team_effect_green',
        'team_effect_blue',
        'team_effect_cyan',
        'team_effect_magenta',
        'team_effect_yellow',
        'team_none_door',
        'team_red_door',
        'team_green_door',
        'team_blue_door',
        'team_cyan_door',
        'team_magenta_door',
        'team_yellow_door',
        'team_none_gate',
        'team_red_gate',
        'team_green_gate',
        'team_blue_gate',
        'team_cyan_gate',
        'team_magenta_gate',
        'team_yellow_gate',
    ]

    public static Foreground = [
        'empty',
        'basic_white',
        'basic_gray',
        'basic_black',
        'basic_red',
        'basic_orange',
        'basic_yellow',
        'basic_green',
        'basic_cyan',
        'basic_blue',
        'basic_magenta',
        'beveled_white',
        'beveled_gray',
        'beveled_black',
        'beveled_red',
        'beveled_orange',
        'beveled_yellow',
        'beveled_green',
        'beveled_cyan',
        'beveled_blue',
        'beveled_magenta',
        'brick_white',
        'brick_gray',
        'brick_black',
        'brick_red',
        'brick_brown',
        'brick_olive',
        'brick_green',
        'brick_teal',
        'brick_blue',
        'brick_purple',
        'checker_white',
        'checker_gray',
        'checker_black',
        'checker_red',
        'checker_orange',
        'checker_yellow',
        'checker_green',
        'checker_cyan',
        'checker_blue',
        'checker_magenta',
        'grass_brick_left',
        'grass_brick_middle',
        'grass_brick_right',
        'metal_silver',
        'metal_copper',
        'metal_gold',
        'generic_striped_hazard_yellow',
        'generic_striped_hazard_black',
        'generic_yellow_face',
        'generic_yellow',
        'generic_black',
        'generic_black_transparent',
        'secret_appear',
        'secret_disappear',
        'secret_invisible',
        'glass_red',
        'glass_orange',
        'glass_yellow',
        'glass_green',
        'glass_cyan',
        'glass_blue',
        'glass_purple',
        'glass_magenta',
        'minerals_red',
        'minerals_orange',
        'minerals_yellow',
        'minerals_green',
        'minerals_cyan',
        'minerals_blue',
        'minerals_purple',
        'minerals_magenta',
        'factory_crate_metal',
        'factory_crate_wood',
        'factory_stone',
        'factory_wood',
        'factory_scales',
        'candy_pink',
        'candy_blue',
        'candy_oneway_pink_top',
        'candy_oneway_red_top',
        'candy_oneway_cyan_top',
        'candy_oneway_green_top',
        'candy_cane',
        'candy_licorice',
        'candy_chocolate',
        'beach_sand',
        'beach_parasol',
        'beach_sand_drift_bottom_left',
        'beach_sand_drift_top_left',
        'beach_sand_drift_top_right',
        'beach_sand_drift_bottom_right',
        'beach_rock',
        'beach_dry_bush',
        'summer_beach',
        'summer_pail',
        'summer_shovel',
        'summer_drink',
        'beach_life_preserver_ring_red',
        'beach_anchor',
        'beach_dock_rope_left',
        'beach_dock_rope_right',
        'beach_tree_palm',
        'jungle_face_block',
        'jungle_oneway_top',
        'jungle_gray',
        'jungle_red',
        'jungle_blue',
        'jungle_olive',
        'jungle_pot',
        'jungle_plant',
        'jungle_pot_broken',
        'jungle_statue',
        'environment_log',
        'environment_grass',
        'environment_bamboo',
        'environment_obsidian',
        'environment_lava',
        'window_clear',
        'window_red',
        'window_orange',
        'window_yellow',
        'window_green',
        'window_teal',
        'window_blue',
        'window_purple',
        'window_pink',
        'canvas_red',
        'canvas_blue',
        'canvas_green',
        'stone_gray',
        'stone_green',
        'stone_brown',
        'stone_blue',
        'gemstone_green',
        'gemstone_purple',
        'gemstone_yellow',
        'gemstone_blue',
        'gemstone_red',
        'gemstone_cyan',
        'gemstone_white',
        'gemstone_black',
        'sand_white',
        'sand_white_surface',
        'sand_gray',
        'sand_gray_surface',
        'sand_yellow',
        'sand_yellow_surface',
        'sand_orange',
        'sand_orange_surface',
        'sand_brown_light',
        'sand_brown_light_surface',
        'sand_brown_dark',
        'sand_brown_dark_surface',
        'farm_wheat',
        'farm_corn',
        'farm_fence_left',
        'farm_fence_middle',
        'farm_fence_right',
        'farm_hay',
        'halloween_blood',
        'halloween_brick_gray',
        'halloween_tombstone',
        'halloween_cobweb_bottom_left',
        'halloween_cobweb_top_left',
        'halloween_cobweb_top_right',
        'halloween_cobweb_bottom_right',
        'halloween_tree_branch_bottom_left',
        'halloween_tree_branch_top_left',
        'halloween_tree_branch_top_right',
        'halloween_tree_branch_bottom_right',
        'halloween_pumpkin_on',
        'halloween_pumpkin_off',
        'halloween_grass_purple',
        'halloween_eyes_yellow',
        'halloween_eyes_orange',
        'halloween_eyes_purple',
        'halloween_eyes_green',
        'marble_column_top',
        'marble_column_middle',
        'marble_column_bottom',
        'marble_gray',
        'marble_green',
        'marble_red',
        'marble_oneway',
        'wildwest_oneway_brown_top',
        'wildwest_oneway_brown_dark_top',
        'wildwest_oneway_red_top',
        'wildwest_oneway_red_dark_top',
        'wildwest_oneway_blue_top',
        'wildwest_oneway_blue_dark_top',
        'wildwest_pole_white_horizontal',
        'wildwest_pole_white_vertical',
        'wildwest_pole_gray_horizontal',
        'wildwest_pole_gray_vertical',
        'wildwest_door_left_brown',
        'wildwest_door_left_red',
        'wildwest_door_left_blue',
        'wildwest_door_right_brown',
        'wildwest_door_right_red',
        'wildwest_door_right_blue',
        'wildwest_window',
        'wildwest_fence_brown_light',
        'wildwest_fence_brown_dark',
        'wildwest_fence_red_light',
        'wildwest_fence_red_dark',
        'wildwest_fence_blue_light',
        'wildwest_fence_blue_dark',
        'cloud_white_center',
        'cloud_white_top',
        'cloud_white_bottom',
        'cloud_white_left',
        'cloud_white_right',
        'cloud_white_top_right',
        'cloud_white_top_left',
        'cloud_white_bottom_left',
        'cloud_white_bottom_right',
        'cloud_gray_center',
        'cloud_gray_top',
        'cloud_gray_bottom',
        'cloud_gray_left',
        'cloud_gray_right',
        'cloud_gray_top_right',
        'cloud_gray_top_left',
        'cloud_gray_bottom_left',
        'cloud_gray_bottom_right',
        'industrial_iron',
        'industrial_wires',
        'industrial_oneway_gray_top',
        'industrial_scaffolding_horizontal',
        'industrial_scaffolding_vertical',
        'industrial_piston_left',
        'industrial_piston_top',
        'industrial_piston_right',
        'industrial_piston_bottom',
        'industrial_pipe_thick_horizontal',
        'industrial_pipe_thick_vertical',
        'industrial_pipe_thin_horizontal',
        'industrial_pipe_thin_vertical',
        'industrial_conveyor_left',
        'industrial_conveyor_middle_peg',
        'industrial_conveyor_middle',
        'industrial_conveyor_right',
        'industrial_caution_sign_fire',
        'industrial_caution_sign_death',
        'industrial_caution_sign_electricity',
        'industrial_caution_sign_entry',
        'industrial_caution_tape_horizontal',
        'industrial_caution_tape_vertical',
        'industrial_pipe_decoration_horizontal',
        'industrial_pipe_decoration_vertical',
        'industrial_lamp_overhead',
        'industrial_tesla_coil',
        'industrial_wire_horizontal',
        'industrial_wire_vertical',
        'industrial_electricity',
        'medieval_oneway_gray_top',
        'medieval_brick',
        'medieval_brick_window',
        'medieval_anvil',
        'medieval_barrel',
        'medieval_blinds',
        'medieval_brick_decoration_top_middle',
        'medieval_stone',
        'medieval_scaffolding_straight_horizontal',
        'medieval_scaffolding_straight_t',
        'medieval_scaffolding_straight_vertical',
        'medieval_scaffolding_angled_left',
        'medieval_scaffolding_angled_middle',
        'medieval_scaffolding_angled_right',
        'medieval_axe_bottom_left',
        'medieval_axe_top_left',
        'medieval_axe_top_right',
        'medieval_axe_bottom_right',
        'medieval_sword_top_right',
        'medieval_sword_bottom_right',
        'medieval_sword_bottom_left',
        'medieval_sword_top_left',
        'medieval_shield_circle_red',
        'medieval_shield_circle_blue',
        'medieval_shield_circle_green',
        'medieval_shield_circle_yellow',
        'medieval_shield_curved_red',
        'medieval_shield_curved_blue',
        'medieval_shield_curved_green',
        'medieval_shield_curved_yellow',
        'medieval_banner_red',
        'medieval_banner_blue',
        'medieval_banner_green',
        'medieval_banner_yellow',
        'medieval_shield',
        'pipes_left',
        'pipes_up',
        'pipes_right',
        'pipes_down',
        'pipes_horizontal',
        'pipes_vertical',
        'outerspace_white',
        'outerspace_blue',
        'outerspace_green',
        'outerspace_red',
        'outerspace_red',
        'outerspace_red',
        'outerspace_sand',
        'outerspace_sand',
        'outerspace_sand',
        'outerspace_moon',
        'outerspace_moon',
        'outerspace_moon',
        'outerspace_mars_rock_1',
        'outerspace_mars_rock_1',
        'outerspace_mars_rock_1',
        'outerspace_mars_rock_2',
        'outerspace_mars_rock_2',
        'outerspace_mars_rock_2',
        'outerspace_mars_rock_3',
        'outerspace_mars_rock_3',
        'outerspace_mars_rock_3',
        'outerspace_mars_rock_4',
        'outerspace_mars_rock_4',
        'outerspace_mars_rock_4',
        'outerspace_mars_rock_5',
        'outerspace_mars_rock_5',
        'outerspace_mars_rock_5',
        'outerspace_sign',
        'outerspace_sign',
        'outerspace_sign',
        'outerspace_light_red',
        'outerspace_light_red',
        'outerspace_light_red',
        'outerspace_light_blue',
        'outerspace_light_blue',
        'outerspace_light_blue',
        'outerspace_light_green',
        'outerspace_light_green',
        'outerspace_light_green',
        'outerspace_light_yellow',
        'outerspace_light_yellow',
        'outerspace_light_yellow',
        'outerspace_light_magenta',
        'outerspace_light_magenta',
        'outerspace_light_magenta',
        'outerspace_light_cyan',
        'outerspace_light_cyan',
        'outerspace_light_cyan',
        'outerspace_computer',
        'outerspace_computer',
        'outerspace_computer',
        'outerspace_star_red',
        'outerspace_star_red',
        'outerspace_star_red',
        'outerspace_star_blue',
        'outerspace_star_blue',
        'outerspace_star_blue',
        'outerspace_star_yellow',
        'outerspace_star_yellow',
        'outerspace_star_yellow',
        'outerspace_rock_gray',
        'outerspace_rock_gray',
        'outerspace_rock_gray',
        'garden_rock',
        'garden_rock',
        'garden_rock',
        'garden_grass',
        'garden_grass',
        'garden_grass',
        'garden_leaves',
        'garden_leaves',
        'garden_leaves',
        'garden_grassplant',
        'garden_grassplant',
        'garden_grassplant',
        'garden_fence',
        'garden_fence',
        'garden_fence',
        'garden_lattice',
        'garden_lattice',
        'garden_lattice',
        'garden_oneway_leaf_branch',
        'garden_oneway_leaf_branch',
        'garden_oneway_leaf_branch',
        'garden_oneway_leaf_left',
        'garden_oneway_leaf_left',
        'garden_oneway_leaf_left',
        'garden_oneway_leaf_right',
        'garden_oneway_leaf_right',
        'garden_oneway_leaf_right',
        'garden_snail',
        'garden_snail',
        'garden_snail',
        'garden_butterfly',
        'garden_butterfly',
        'garden_butterfly',
        'garden_frame',
        'garden_frame',
        'garden_frame',
        'domestic_tile',
        'domestic_tile',
        'domestic_tile',
        'domestic_wood',
        'domestic_wood',
        'domestic_wood',
        'domestic_wood_panel',
        'domestic_wood_panel',
        'domestic_wood_panel',
        'domestic_lamp',
        'domestic_lamp',
        'domestic_lamp',
        'domestic_light_bulb_bottom_off',
        'domestic_light_bulb_bottom_off',
        'domestic_light_bulb_bottom_off',
        'domestic_light_bulb_bottom_on',
        'domestic_light_bulb_bottom_on',
        'domestic_light_bulb_bottom_on',
        'domestic_light_bulb_top_off',
        'domestic_light_bulb_top_off',
        'domestic_light_bulb_top_off',
        'domestic_light_bulb_top_on',
        'domestic_light_bulb_top_on',
        'domestic_light_bulb_top_on',
        'domestic_pipe_bottom_left',
        'domestic_pipe_bottom_left',
        'domestic_pipe_bottom_left',
        'domestic_pipe_top_left',
        'domestic_pipe_top_left',
        'domestic_pipe_top_left',
        'domestic_pipe_top_right',
        'domestic_pipe_top_right',
        'domestic_pipe_top_right',
        'domestic_bottom_right',
        'domestic_bottom_right',
        'domestic_bottom_right',
        'domestic_pipe_cross',
        'domestic_pipe_cross',
        'domestic_pipe_cross',
        'domestic_pipe_straight_horizontal',
        'domestic_pipe_straight_horizontal',
        'domestic_pipe_straight_horizontal',
        'domestic_pipe_straight_vertical',
        'domestic_pipe_straight_vertical',
        'domestic_pipe_straight_vertical',
        'domestic_pipe_t_bottom',
        'domestic_pipe_t_bottom',
        'domestic_pipe_t_bottom',
        'domestic_pipe_t_left',
        'domestic_pipe_t_left',
        'domestic_pipe_t_left',
        'domestic_pipe_t_top',
        'domestic_pipe_t_top',
        'domestic_pipe_t_top',
        'domestic_pipe_t_right',
        'domestic_pipe_t_right',
        'domestic_pipe_t_right',
        'domestic_painting_purple',
        'domestic_painting_purple',
        'domestic_painting_purple',
        'domestic_painting_blue',
        'domestic_painting_blue',
        'domestic_painting_blue',
        'domestic_painting_blue_dark',
        'domestic_painting_blue_dark',
        'domestic_painting_blue_dark',
        'domestic_painting_green',
        'domestic_painting_green',
        'domestic_painting_green',
        'domestic_vase_blue',
        'domestic_vase_blue',
        'domestic_vase_blue',
        'domestic_vase_purple',
        'domestic_vase_purple',
        'domestic_vase_purple',
        'domestic_vase_orange',
        'domestic_vase_orange',
        'domestic_vase_orange',
        'domestic_vase_yellow',
        'domestic_vase_yellow',
        'domestic_vase_yellow',
        'domestic_television_black',
        'domestic_television_black',
        'domestic_television_black',
        'domestic_television_blue',
        'domestic_television_gray',
        'domestic_television_yellow',
        'domestic_window_black',
        'domestic_window_blue',
        'domestic_window_orange',
        'domestic_window_yellow',
        'domestic_half_yellow_left',
        'domestic_half_yellow_top',
        'domestic_half_yellow_right',
        'domestic_half_yellow_bottom',
        'domestic_half_brown_left',
        'domestic_half_brown_top',
        'domestic_half_brown_right',
        'domestic_half_brown_bottom',
        'domestic_half_white_left',
        'domestic_half_white_top',
        'domestic_half_white_right',
        'domestic_half_white_bottom',
        'domestic_frame_border_full',
        'domestic_frame_border_left',
        'domestic_frame_border_top',
        'domestic_frame_border_right',
        'domestic_frame_border_bottom',
        'domestic_frame_border_top_left',
        'domestic_frame_border_top_right',
        'domestic_frame_border_bottom_left',
        'domestic_frame_border_bottom_right',
        'domestic_frame_border_left_right',
        'domestic_frame_border_top_bottom',
        'dojo_oneway_white_top',
        'dojo_oneway_gray_top',
        'dojo_rooftop_blue_left',
        'dojo_rooftop_blue_dark_left',
        'dojo_rooftop_red_left',
        'dojo_rooftop_red_dark_left',
        'dojo_rooftop_green_left',
        'dojo_rooftop_green_dark_left',
        'dojo_rooftop_blue_right',
        'dojo_rooftop_blue_dark_right',
        'dojo_rooftop_red_right',
        'dojo_rooftop_red_dark_right',
        'dojo_rooftop_green_right',
        'dojo_rooftop_green_dark_right',
        'dojo_window_bright',
        'dojo_window_dark',
        'dojo_chinese_character_and',
        'dojo_chinese_character_book',
        'dojo_chinese_symbol_yin_yang',
        'christmas_tree_plain',
        'christmas_tree_lights',
        'christmas_fence_snow',
        'christmas_fence_plain',
        'christmas_ornament_red',
        'christmas_ornament_green',
        'christmas_ornament_blue',
        'christmas_wreath',
        'christmas_star',
        'christmas_ribbon_blue_vertical',
        'christmas_ribbon_blue_horizontal',
        'christmas_ribbon_blue_cross',
        'christmas_ribbon_purple_vertical',
        'christmas_ribbon_purple_horizontal',
        'christmas_ribbon_purple_cross',
        'christmas_candy_cane',
        'christmas_mistletoe',
        'christmas_stocking',
        'christmas_ribbon_red_bow',
        'christmas_gift_full_red',
        'christmas_gift_half_red',
        'christmas_gift_full_green',
        'christmas_gift_half_green',
        'christmas_gift_full_white',
        'christmas_gift_half_white',
        'christmas_gift_full_blue',
        'christmas_gift_half_blue',
        'christmas_gift_full_yellow',
        'christmas_gift_half_yellow',
        'christmas_string_light_bottom_red',
        'christmas_string_light_bottom_green',
        'christmas_string_light_bottom_blue',
        'christmas_string_light_bottom_purple',
        'christmas_string_light_bottom_yellow',
        'christmas_string_light_top_red',
        'christmas_string_light_top_green',
        'christmas_string_light_top_blue',
        'christmas_string_light_top_purple',
        'christmas_string_light_top_yellow',
        'christmas_bell_yellow',
        'christmas_bell_group_red',
        'christmas_candle_red',
        'scifi_panel_red',
        'scifi_panel_blue',
        'scifi_panel_green',
        'scifi_panel_yellow',
        'scifi_panel_magenta',
        'scifi_panel_cyan',
        'scifi_metal_gray',
        'scifi_metal_white',
        'scifi_brown_leopard',
        'scifi_oneway_red_top',
        'scifi_oneway_blue_top',
        'scifi_oneway_green_top',
        'scifi_oneway_yellow_top',
        'scifi_oneway_magenta_top',
        'scifi_oneway_cyan_top',
        'scifi_laser_blue_straight_horizontal',
        'scifi_laser_blue_straight_vertical',
        'scifi_laser_blue_corner_topleft',
        'scifi_laser_blue_corner_topright',
        'scifi_laser_blue_corner_bottomright',
        'scifi_laser_blue_corner_bottomleft',
        'scifi_laser_green_straight_horizontal',
        'scifi_laser_green_straight_vertical',
        'scifi_laser_green_corner_topleft',
        'scifi_laser_green_corner_topright',
        'scifi_laser_green_corner_bottomright',
        'scifi_laser_green_corner_bottomleft',
        'scifi_laser_orange_straight_horizontal',
        'scifi_laser_orange_straight_veritical',
        'scifi_laser_orange_corner_topleft',
        'scifi_laser_orange_corner_topright',
        'scifi_laser_orange_corner_bottomright',
        'scifi_laser_orange_corner_bottomleft',
        'scifi_laser_red_straight_horizontal',
        'scifi_laser_red_straight_vertical',
        'scifi_laser_red_corner_topleft',
        'scifi_laser_red_corner_topright',
        'scifi_laser_red_corner_bottomright',
        'scifi_laser_red_corner_bottomleft',
        'prison_bars',
        'prison_brick',
        'pirate_wood_plank_brown',
        'pirate_chest_brown',
        'pirate_oneway_brown_top',
        'pirate_ship_border_brown',
        'pirate_skeleton_head',
        'pirate_cannon',
        'pirate_port_window',
        'plastic_red',
        'plastic_orange',
        'plastic_yellow',
        'plastic_lime',
        'plastic_green',
        'plastic_cyan',
        'plastic_blue',
        'plastic_magenta',
        'lava_yellow',
        'lava_orange',
        'lava_dark_orange',
        'gold_basic',
        'gold_brick',
        'gold_chisled',
        'gold_tile',
        'gold_mantle_oneway_top',
        'construction_plywood',
        'construction_gravel',
        'construction_cement',
        'construction_beam_red_horizontal_left',
        'construction_beam_red_horizontal_middle',
        'construction_beam_red_horizontal_right',
        'construction_beam_red_vertical_top',
        'construction_beam_red_vertical_middle',
        'construction_beam_red_vertical_bottom',
        'construction_caution_orange',
        'construction_cone_orange',
        'construction_sign_warning',
        'construction_sign_stop',
        'construction_hydrant_fire',
        'tiles_white',
        'tiles_gray',
        'tiles_black',
        'tiles_red',
        'tiles_orange',
        'tiles_yellow',
        'tiles_green',
        'tiles_cyan',
        'tiles_blue',
        'tiles_purple',
        'halfblocks_white_left',
        'halfblocks_white_top',
        'halfblocks_white_right',
        'halfblocks_white_bottom',
        'halfblocks_gray_left',
        'halfblocks_gray_top',
        'halfblocks_gray_right',
        'halfblocks_gray_bottom',
        'halfblocks_black_left',
        'halfblocks_black_top',
        'halfblocks_black_right',
        'halfblocks_black_bottom',
        'halfblocks_red_left',
        'halfblocks_red_top',
        'halfblocks_red_right',
        'halfblocks_red_bottom',
        'halfblocks_orange_left',
        'halfblocks_orange_top',
        'halfblocks_orange_right',
        'halfblocks_orange_bottom',
        'halfblocks_yellow_left',
        'halfblocks_yellow_top',
        'halfblocks_yellow_right',
        'halfblocks_yellow_bottom',
        'halfblocks_green_left',
        'halfblocks_green_top',
        'halfblocks_green_right',
        'halfblocks_green_bottom',
        'halfblocks_cyan_left',
        'halfblocks_cyan_top',
        'halfblocks_cyan_right',
        'halfblocks_cyan_bottom',
        'halfblocks_blue_left',
        'halfblocks_blue_top',
        'halfblocks_blue_right',
        'halfblocks_blue_bottom',
        'halfblocks_magenta_left',
        'halfblocks_magenta_top',
        'halfblocks_magenta_right',
        'halfblocks_magenta_bottom',
        'winter_ice_brick',
        'winter_snow',
        'winter_glacier',
        'winter_slate',
        'winter_ice',
        'winter_oneway_ice',
        'winter_ice_light',
        'winter_ice_dark',
        'winter_ice_dark_left',
        'winter_ice_dark_middle',
        'winter_ice_dark_right',
        'winter_half_snow_left',
        'winter_half_snow_top',
        'winter_half_snow_right',
        'winter_half_snow_bottom',
        'winter_half_ice_left',
        'winter_half_ice_top',
        'winter_half_ice_right',
        'winter_half_ice_bottom',
        'winter_ice_slippery',
        'winter_snow_pile',
        'winter_ice_drift_bottom_left',
        'winter_ice_drift_top_left',
        'winter_ice_drift_top_right',
        'winter_ice_drift_bottom_right',
        'winter_snow_drift_bottom_left',
        'winter_snow_drift_top_left',
        'winter_snow_drift_top_right',
        'winter_snow_drift_bottom_right',
        'winter_snow_fluff_left',
        'winter_snow_fluff_middle',
        'winter_snow_fluff_right',
        'winter_snowman',
        'winter_tree',
        'winter_snowflake_large',
        'winter_snowflake_small',
        'fairytale_pebbles',
        'fairytale_tree_orange',
        'fairytale_moss_green',
        'fairytale_cloud_blue',
        'fairytale_mushroom_block_red',
        'fairytale_vine_green',
        'fairytale_mushroom_decoration_orange',
        'fairytale_mushroom_decoration_red',
        'fairytale_dew_drop',
        'fairytale_half_orange_left',
        'fairytale_half_orange_top',
        'fairytale_half_orange_right',
        'fairytale_half_orange_bottom',
        'fairytale_half_green_left',
        'fairytale_half_green_top',
        'fairytale_half_green_right',
        'fairytale_half_green_bottom',
        'fairytale_half_blue_left',
        'fairytale_half_blue_top',
        'fairytale_half_blue_right',
        'fairytale_half_blue_bottom',
        'fairytale_half_pink_left',
        'fairytale_half_pink_top',
        'fairytale_half_pink_right',
        'fairytale_half_pink_bottom',
        'fairytale_flower_pink',
        'fairytale_flower_blue',
        'fairytale_flower_orange',
        'spring_dirt_brown',
        'spring_hedge_green',
        'spring_dirt_drift_bottom_left',
        'spring_dirt_drift_top_left',
        'spring_dirt_drift_top_right',
        'spring_dirt_drift_bottom_right',
        'spring_daisy_pink',
        'spring_daisy_white',
        'spring_daisy_blue',
        'spring_tulip_pink',
        'spring_tulip_red',
        'spring_tulip_yellow',
        'spring_daffodil_orange',
        'spring_daffodil_yellow',
        'spring_daffodil_white',
        'oneway_white_left',
        'oneway_white_top',
        'oneway_white_right',
        'oneway_white_bottom',
        'oneway_gray_left',
        'oneway_gray_top',
        'oneway_gray_right',
        'oneway_gray_bottom',
        'oneway_black_left',
        'oneway_black_top',
        'oneway_black_right',
        'oneway_black_bottom',
        'oneway_red_left',
        'oneway_red_top',
        'oneway_red_right',
        'oneway_red_bottom',
        'oneway_orange_left',
        'oneway_orange_top',
        'oneway_orange_right',
        'oneway_orange_bottom',
        'oneway_yellow_left',
        'oneway_yellow_top',
        'oneway_yellow_right',
        'oneway_yellow_bottom',
        'oneway_green_left',
        'oneway_green_top',
        'oneway_green_right',
        'oneway_green_bottom',
        'oneway_cyan_left',
        'oneway_cyan_top',
        'oneway_cyan_right',
        'oneway_cyan_bottom',
        'oneway_blue_left',
        'oneway_blue_top',
        'oneway_blue_right',
        'oneway_blue_bottom',
        'oneway_magenta_left',
        'oneway_magenta_top',
        'oneway_magenta_right',
        'oneway_magenta_bottom',
        'dungeon_cobblestone_grey',
        'dungeon_cobblestone_green',
        'dungeon_cobblestone_blue',
        'dungeon_cobblestone_purple',
        'dungeon_pillar_bottom_purple',
        'dungeon_pillar_bottom_gray',
        'dungeon_pillar_bottom_green',
        'dungeon_pillar_bottom_blue',
        'dungeon_pillar_middle_purple',
        'dungeon_pillar_middle_gray',
        'dungeon_pillar_middle_green',
        'dungeon_pillar_middle_blue',
        'dungeon_oneway_pillar_top_purple',
        'dungeon_oneway_pillar_top_gray',
        'dungeon_oneway_pillar_top_green',
        'dungeon_oneway_pillar_top_blue',
        'dungeon_steel_arc_left_purple',
        'dungeon_steel_arc_left_gray',
        'dungeon_steel_arc_left_green',
        'dungeon_steel_arc_left_blue',
        'dungeon_pillar_arc_right_purple',
        'dungeon_pillar_arc_right_gray',
        'dungeon_pillar_arc_right_green',
        'dungeon_pillar_arc_right_blue',
        'dungeon_torch_purple',
        'dungeon_torch_yellow',
        'dungeon_torch_blue',
        'dungeon_torch_green',
        'dungeon_window',
        'dungeon_chain_ring',
        'dungeon_chain_hook',
        'dungeon_chain_lock',
        'retail_flag_purple',
        'retail_flag_red',
        'retail_flag_yellow',
        'retail_flag_green',
        'retail_flag_cyan',
        'retail_flag_blue',
        'retail_awning_purple',
        'retail_awning_red',
        'retail_awning_yellow',
        'retail_awning_green',
        'retail_awning_cyan',
        'retail_awning_blue',
        'summer_straw',
        'summer_plank_purple',
        'summer_plank_yelllow',
        'summer_plank_green',
        'summer_oneway_dock_top',
        'summer_ice_cream_mint',
        'summer_ice_cream_vanilla',
        'summer_ice_cream_chocolate',
        'summer_ice_cream_srawberry',
        'mine_stone_brown',
        'mine_stalagmite',
        'mine_stalagtite',
        'mine_crystal_purple',
        'mine_crystal_red',
        'mine_crystal_yellow',
        'mine_crystal_green',
        'mine_crystal_cyan',
        'mine_crystal_blue',
        'mine_torch',
        'haunted_mossy_brick_green',
        'haunted_siding_gray',
        'haunted_mossy_shingles_gray',
        'haunted_oneway_stone_gray_top',
        'haunted_bush_dead',
        'haunted_fence_iron',
        'haunted_window_curved_off',
        'haunted_window_curved_on',
        'haunted_window_circle_off',
        'haunted_window_circle_on',
        'haunted_lantern_off',
        'haunted_lantern_on',
        'desert_rock_orange',
        'desert_cactus',
        'desert_bush',
        'desert_tree',
        'monster_teeth_large_left',
        'monster_teeth_large_top',
        'monster_teeth_large_right',
        'monster_teeth_large_bottom',
        'monster_teeth_medium_left',
        'monster_teeth_medium_top',
        'monster_teeth_medium_right',
        'monster_teeth_medium_bottom',
        'monster_teeth_small_left',
        'monster_teeth_small_top',
        'monster_teeth_small_right',
        'monster_teeth_small_bottom',
        'monster_eye_purple',
        'monster_eye_yellow',
        'monster_eye_blue',
        'swamp_grass',
        'swamp_log',
        'swamp_sign_toxic',
        'fall_leaves_drift_bottom_left',
        'fall_leaves_drift_top_left',
        'fall_leaves_drift_top_right',
        'fall_leaves_drift_bottom_right',
        'fall_grass_left',
        'fall_grass_middle',
        'fall_grass_right',
        'fall_acorn',
        'fall_pumpkin',
        'valentines_heart_red',
        'valentines_heart_purple',
        'valentines_heart_pink',
        'newyears_hung_light_red',
        'newyears_hung_light_yellow',
        'newyears_hung_light_green',
        'newyears_hung_light_blue',
        'newyears_hung_light_pink',
        'newyears_wine',
        'newyears_champagne',
        'newyears_balloon_red',
        'newyears_balloon_orange',
        'newyears_balloon_green',
        'newyears_balloon_blue',
        'newyears_balloon_purple',
        'newyears_streamer_red',
        'newyears_streamer_orange',
        'newyears_streamer_green',
        'newyears_streamer_blue',
        'newyears_streamer_purple',
        'leprechaun_shamrock',
        'leprechaun_gold_pot',
        'leprechaun_gold_bag',
        'leprechaun_horse_shoe',
        'leprechaun_rainbow_left',
        'leprechaun_rainbow_right',
        'restaurant_food_burger',
        'restaurant_food_hotdog',
        'restaurant_food_sub',
        'restaurant_food_soda',
        'restaurant_food_fries',
        'restaurant_glass_water',
        'restaurant_glass_milk',
        'restaurant_glass_orangejuice',
        'restaurant_glass_empty',
        'restaurant_plate_chicken',
        'restaurant_plate_ham',
        'restaurant_plate_fish',
        'restaurant_plate_cookies',
        'restaurant_plate_empty',
        'restaurant_bowl_salad',
        'restaurant_bowl_spaghetti',
        'restaurant_bowl_icecream',
        'restaurant_bowl_empty',
        'toxic_oneway_rusted_left',
        'toxic_oneway_rusted_top',
        'toxic_oneway_rusted_right',
        'toxic_oneway_rusted_bottom',
        'toxic_waste_barrel_on',
        'toxic_waste_barrel_off',
        'toxic_sewer_drain_waste',
        'toxic_sewer_drain_empty',
        'toxic_sewer_drain_water',
        'toxic_sewer_drain_lava',
        'toxic_sewer_drain_mud',
        'toxic_ladder_vertical_broken',
        'toxic_rail_rusted',
    ] as const

    public static Decoration = [
        'liquid_water_surface',
        'liquid_waste_surface',
        'liquid_lava_surface',
        'liquid_mud_surface',
        'meadow_grass_left',
        'meadow_grass_middle',
        'meadow_grass_right',
        'meadow_bush_left',
        'meadow_bush_middle',
        'meadow_bush_right',
        'meadow_yellow_flower',
        'meadow_small_bush',
        'easter_egg_blue',
        'easter_egg_pink',
        'easter_egg_yellow',
        'easter_egg_red',
        'easter_egg_green',
        'candy_cream_small',
        'candy_cream_large',
        'candy_gumdrop_red',
        'candy_gumdrop_green',
        'candy_gumdrop_pink',

    ]

    public static Background: (((keyof typeof BlockMappings) & `${string}_bg`) | 'empty')[] =
        Object.keys(BlockMappings).filter(bg => bg.endsWith('_bg') || bg === 'empty') as any

    // public static Background = [
    //     'empty',
    //     'basic_white_bg',
    //     'basic_gray_bg',
    //     'basic_black_bg',
    //     'basic_red_bg',
    //     'basic_orange_bg',
    //     'basic_yellow_bg',
    //     'basic_green_bg',
    //     'basic_cyan_bg',
    //     'basic_blue_bg',
    //     'basic_magenta_bg',
    //     'brick_white_bg',
    //     'brick_gray_bg',
    //     'brick_black_bg',
    //     'brick_red_bg',
    //     'brick_brown_bg',
    //     'brick_olive_bg',
    //     'brick_green_bg',
    //     'brick_teal_bg',
    //     'brick_blue_bg',
    //     'brick_purple_bg',
    //     'normal_white_bg',
    //     'normal_gray_bg',
    //     'normal_black_bg',
    //     'normal_red_bg',
    //     'normal_orange_bg',
    //     'normal_yellow_bg',
    //     'normal_green_bg',
    //     'normal_cyan_bg',
    //     'normal_blue_bg',
    //     'normal_magenta_bg',
    //     'dark_white_bg',
    //     'dark_gray_bg',
    //     'dark_black_bg',
    //     'dark_red_bg',
    //     'dark_orange_bg',
    //     'dark_yellow_bg',
    //     'dark_green_bg',
    //     'dark_cyan_bg',
    //     'dark_blue_bg',
    //     'dark_magenta_bg',
    //     'checker_white_bg',
    //     'checker_gray_bg',
    //     'checker_black_bg',
    //     'checker_red_bg',
    //     'checker_orange_bg',
    //     'checker_yellow_bg',
    //     'checker_green_bg',
    //     'checker_cyan_bg',
    //     'checker_blue_bg',
    //     'checker_magenta_bg',
    //     'pastel_red_bg',
    //     'pastel_orange_bg',
    //     'pastel_yellow_bg',
    //     'pastel_lime_bg',
    //     'pastel_green_bg',
    //     'pastel_cyan_bg',
    //     'pastel_blue_bg',
    //     'pastel_purple_bg',
    //     'candy_pink_bg',
    //     'candy_blue_bg',
    //     'jungle_gray_bg',
    //     'jungle_red_bg',
    //     'jungle_blue_bg',
    //     'jungle_olive_bg',
    //     'jungle_leaves_light_bg',
    //     'jungle_leaves_medium_bg',
    //     'jungle_leaves_dark_bg',
    //     'environment_log_bg',
    //     'environment_grass_bg',
    //     'environment_bamboo_bg',
    //     'environment_obsidian_bg',
    //     'environment_lava_bg',
    //     'canvas_gray_bg',
    //     'canvas_red_bg',
    //     'canvas_orange_bg',
    //     'canvas_tan_bg',
    //     'canvas_yellow_bg',
    //     'canvas_green_bg',
    //     'canvas_cyan_bg',
    //     'canvas_blue_bg',
    //     'canvas_purple_bg',
    //     'stone_gray_bg',
    //     'stone_half_gray_bg',
    //     'stone_green_bg',
    //     'stone_half_green_bg',
    //     'stone_brown_bg',
    //     'stone_half_brown_bg',
    //     'stone_blue_bg',
    //     'stone_half_blue_bg',
    //     'sand_yellow_light_bg',
    //     'sand_gray_bg',
    //     'sand_yellow_dark_bg',
    //     'sand_orange_bg',
    //     'sand_brown_light_bg',
    //     'sand_brown_dark_bg',
    //     'cave_gray_light_bg',
    //     'cave_gray_dark_bg',
    //     'cave_black_bg',
    //     'cave_red_bg',
    //     'cave_brown_bg',
    //     'cave_yellow_bg',
    //     'cave_green_bg',
    //     'cave_cyan_bg',
    //     'cave_blue_bg',
    //     'cave_purple_bg',
    //     'cave_pink_bg',
    //     'halloween_gray_bg',
    //     'halloween_brick_gray_bg',
    //     'halloween_brick_gray_right_bg',
    //     'halloween_brick_gray_left_bg',
    //     'halloween_tree_bg',
    //     'halloween_leaves_purple_bg',
    //     'marble_gray_bg',
    //     'marble_green_bg',
    //     'marble_red_bg',
    //     'wildwest_siding_brown_light_bg',
    //     'wildwest_siding_brown_dark_bg',
    //     'wildwest_siding_red_light_bg',
    //     'wildwest_siding_red_dark_bg',
    //     'wildwest_siding_blue_light_bg',
    //     'wildwest_siding_blue_dark_bg',
    //     'neon_magenta_bg',
    //     'neon_orange_bg',
    //     'neon_yellow_bg',
    //     'neon_green_bg',
    //     'neon_cyan_bg',
    //     'neon_blue_bg',
    //     'industrial_plate_gray_plain_bg',
    //     'industrial_plate_gray_gray_bg',
    //     'industrial_plate_gray_blue_bg',
    //     'industrial_plate_gray_green_bg',
    //     'industrial_plate_gray_yellow_bg',
    //     'clay_tile_white_bg',
    //     'clay_tile_brick_bg',
    //     'clay_tile_diamond_bg',
    //     'clay_tile_x_bg',
    //     'clay_tile_rough_bg',
    //     'medieval_brick_bg',
    //     'medieval_wood_bg',
    //     'medieval_straw_bg',
    //     'medieval_roof_red_bg',
    //     'medieval_roof_green_bg',
    //     'medieval_roof_brown_bg',
    //     'medieval_roof_gray_bg',
    //     'outerspace_white_bg',
    //     'outerspace_white_bg',
    //     'outerspace_white_bg',
    //     'outerspace_blue_bg',
    //     'outerspace_blue_bg',
    //     'outerspace_blue_bg',
    //     'outerspace_green_bg',
    //     'outerspace_green_bg',
    //     'outerspace_green_bg',
    //     'outerspace_red_bg',
    //     'outerspace_red_bg',
    //     'outerspace_red_bg',
    //     'outerspace_mars_rock_3_bg',
    //     'outerspace_mars_rock_3_bg',
    //     'outerspace_mars_rock_3_bg',
    //     'outerspace_mars_rock_4_bg',
    //     'outerspace_mars_rock_4_bg',
    //     'outerspace_mars_rock_4_bg',
    //     'outerspace_mars_rock_5_bg',
    //     'outerspace_mars_rock_5_bg',
    //     'outerspace_mars_rock_5_bg',
    //     'garden_rock_bg',
    //     'garden_rock_bg',
    //     'garden_rock_bg',
    //     'garden_grass_bg',
    //     'garden_grass_bg',
    //     'garden_grass_bg',
    //     'garden_leaves_bg',
    //     'garden_leaves_bg',
    //     'garden_leaves_bg',
    //     'domestic_wallpaper_yellow_bg',
    //     'domestic_wallpaper_yellow_bg',
    //     'domestic_wallpaper_yellow_bg',
    //     'domestic_wallpaper_brown_bg',
    //     'domestic_wallpaper_brown_bg',
    //     'domestic_wallpaper_brown_bg',
    //     'domestic_wallpaper_red_bg',
    //     'domestic_wallpaper_red_bg',
    //     'domestic_wallpaper_red_bg',
    //     'domestic_wallpaper_blue_bg',
    //     'domestic_wallpaper_blue_bg',
    //     'domestic_wallpaper_blue_bg',
    //     'domestic_wallpaper_green_bg',
    //     'domestic_wallpaper_green_bg',
    //     'domestic_wallpaper_green_bg',
    //     'dojo_wallpaper_white_bg',
    //     'dojo_wallpaper_gray_bg',
    //     'dojo_shingles_blue_bg',
    //     'dojo_shingles_blue_dark_bg',
    //     'dojo_shingles_red_bg',
    //     'dojo_shingles_red_dark_bg',
    //     'dojo_shingles_green_bg',
    //     'dojo_shingles_green_dark_bg',
    //     'christmas_wrapping_paper_yellow_bg',
    //     'christmas_wrapping_paper_green_bg',
    //     'christmas_wrapping_paper_blue_bg',
    //     'scifi_outline_gray_bg',
    //     'prison_brick_bg',
    //     'prison_window_orange_bg',
    //     'prison_window_blue_bg',
    //     'prison_window_black_bg',
    //     'pirate_wood_plank_brown_bg',
    //     'pirate_wood_plank_light_brown_bg',
    //     'pirate_wood_plank_dark_brown_bg',
    //     'pirate_skeleton_flag_bg',
    //     'lava_yellow_bg',
    //     'lava_orange_bg',
    //     'lava_dark_red_bg',
    //     'gold_basic_bg',
    //     'gold_brick_bg',
    //     'gold_chisled_bg',
    //     'construction_plywood_bg',
    //     'construction_gravel_bg',
    //     'construction_cement_bg',
    //     'construction_beam_red_horizontal_left_bg',
    //     'construction_beam_red_horizontal_middle_bg',
    //     'construction_beam_red_horizontal_right_bg',
    //     'construction_beam_red_vertical_top_bg',
    //     'construction_beam_red_vertical_middle_bg',
    //     'construction_beam_red_vertical_bottom_bg',
    //     'tiles_white_bg',
    //     'tiles_gray_bg',
    //     'tiles_black_bg',
    //     'tiles_red_bg',
    //     'tiles_orange_bg',
    //     'tiles_yellow_bg',
    //     'tiles_green_bg',
    //     'tiles_cyan_bg',
    //     'tiles_blue_bg',
    //     'tiles_purple_bg',
    //     'winter_ice_dark_bg',
    //     'winter_ice_light_bg',
    //     'winter_ice_brick_bg',
    //     'winter_snow_bg',
    //     'winter_glacier_bg',
    //     'winter_slate_bg',
    //     'fairytale_mist_orange_bg',
    //     'fairytale_mist_green_bg',
    //     'fairytale_mist_blue_bg',
    //     'fairytale_mist_pink_bg',
    //     'dungeon_cobblestone_grey_bg',
    //     'dungeon_cobblestone_green_bg',
    //     'dungeon_cobblestone_blue_bg',
    //     'dungeon_cobblestone_purple_bg',
    //     'summer_straw_bg',
    //     'summer_plank_purple_bg',
    //     'summer_plank_yellow_bg',
    //     'summer_plank_green_bg',
    //     'mine_stone_brown_bg',
    //     'haunted_mossy_brick_green_bg',
    //     'haunted_sliding_gray_bg',
    //     'haunted_mossy_shingles_gray_bg',
    //     'monster_skin_green_light_bg',
    //     'monster_skin_green_dark_bg',
    //     'monster_scales_red_light_bg',
    //     'monster_scales_red_dark_bg',
    //     'monster_scales_purple_light_bg',
    //     'monster_scales_purple_dark_bg',
    //     'swamp_mud_bg',
    //     'swamp_grass_bg',
    //     'fall_leaves_yellow_bg',
    //     'fall_leaves_orange_bg',
    //     'fall_leaves_red_bg',
    //     'toxic_waste_bg',
    //     'textile_cloth_green_bg',
    //     'textile_cloth_blue_bg',
    //     'textile_cloth_pink_bg',
    //     'textile_cloth_yellow_bg',
    //     'textile_cloth_red_bg',
    //     'carnival_stripes_red_white_bg',
    //     'carnival_stripes_red_yellow_bg',
    //     'carnival_stripes_purple_violet_bg',
    //     'carnival_checker_bg',
    //     'carnival_pink_bg',
    //     'carnival_green_bg',
    //     'carnival_yellow_bg',
    //     'carnival_blue_bg',
    //     'underwater_bg',
    //     'underwater_octopus_bg',
    //     'underwater_fish_bg',
    //     'underwater_seahorse_bg',
    //     'underwater_seaweed_bg',
    // ] as const
}
