
name: Build Node Package

on:
    workflow_call:
        # READ MORE https://docs.github.com/en/actions/sharing-automations/reusing-workflows

jobs:
    build-node:
        runs-on: ubuntu-latest
        timeout-minutes: 3

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "21.4.0"
                  registry-url: "https://registry.npmjs.org"

            - name: Install node modules
              run: npm ci

            - name: Build `.proto` files
              run: npm run generate-proto

            - name: Build the binary
              run: npm run build
