# https://gist.github.com/mikroskeem/fddaf7a4f80959d6e5f4711904885fae

name: "Publish documentation"

on:
    push:
        branches:
            - "main"

jobs:
    publish-documentation:
        permissions:
            id-token: "write"
            pages: "write"

        environment:
            name: "github-pages"
            url: "${{ steps.deployment.outputs.page_url }}"

        runs-on: "ubuntu-latest"

        steps:
            - name: Build Package
              uses: Anatoly03/pixelwalker.js/.github/workflows/build.yml@main

            - name: "Building Documentation"
              run: npm run docs

            - id: "upload-documentation"
              name: "Uploading Pages artifact"
              uses: "actions/upload-pages-artifact@v2"
              with:
                  path: "docs/"

            - id: "deployment"
              name: "Deploy to GitHub Pages"
              uses: "actions/deploy-pages@v4"
