
name: Run SDK Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '21.4.0'
    - run: npm install
    - run: npm test